# Arithmetic operation

In [1]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)
varadd1 = np.add(var1,4)

print(varadd)
print(varadd1)

[2 4 6 8]
[5 6 7 8]


In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [3]:
var = np.array([1,2,3,4])

varadd = var - 3

print(varadd)

[-2 -1  0  1]


In [4]:
var = np.array([1,2,3,4])

varadd = var * 3

print(varadd)

[ 3  6  9 12]


In [5]:
var = np.array([1,2,3,4])

varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [4]:
var = np.array([1,2,3,4])
varadd = np.reciprocal(var)
print(varadd)


[1 0 0 0]


In [6]:
var = np.array([1,2,3,4])

varadd = var % 3

print(varadd)

[1 2 0 1]


# 2D Arrray


In [3]:
import numpy as np
var21 = np.array([[1,2,3,4], [1,2,3,4]])
var22 = np.array([[1,2,3,4], [1,2,3,4]])

print(var21)
print()
print(var22)
print()
varadd2 = var21 + var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


min and max

In [8]:
var = np.array([1,2,3,4,5,3,2,1])
print("min : ", np.min(var), np.argmin(var))
print("max : ", np.max(var), np.argmax(var))
print("sqrt :", np.sqrt(var))

min :  1 0
max :  5 4
sqrt : [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356 1.        ]


In [7]:
var1 = np.array([[2,3,4],[9,5,6]])
print(np.min(var1, axis=0))


[2 3 4]


In [11]:
var2 = np.array([2,3,4])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]
[2 5 9]
