# random

rand()

In [1]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.88445032 0.95381102 0.92972387 0.89286614]


In [2]:
var1 = np.random.rand(2,5)
print(var1)

[[0.91084045 0.05220382 0.67655067 0.01885325 0.95947265]
 [0.81114625 0.77227187 0.02217529 0.76492619 0.92607283]]


randn()

In [3]:
var2 = np.random.randn(4)
print(var2)

[ 1.15153729 -0.85475034  0.84614908  0.35831649]


ranf() include 0 not 1 [0,1)

In [4]:
var3 = np.random.ranf(4)
print(var3)

[0.48738451 0.77405598 0.90013226 0.95201301]


randint() minimum value , maximum value, total value genrate

In [7]:
var4 = np.random.randint(5,20,5)
print(var4)

[10  9 14 15  5]
