# Data Type

In [4]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print("Data Type : ", var.dtype)

Data Type :  int64


In [3]:
var = np.array([1.04, 3.45, 3.44565])
print("Data Type : ", var.dtype)

Data Type :  float64


In [6]:
var = np.array(["A", "C", "W"])
print("Data Type : ", var.dtype)

Data Type :  <U1


In [7]:
var = np.array(["A", "C", "W", 2, 3, 4 ,4 ])
print("Data Type : ", var.dtype)

Data Type :  <U21


In [2]:
import numpy as np
x = np.array([1,2,3,4],dtype= np.int8)
print("Data Type: ",x.dtype)
print(x)

Data Type:  int8
[1 2 3 4]


In [3]:
x1 = np.array([1,2,3,4],dtype= "f")

print("Data Type: ",x1.dtype)
print(x1)

Data Type:  float32
[1. 2. 3. 4.]


In [4]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
print("Data Type: ",x2.dtype)
print("Data Type: ",new.dtype)

print(x2)
print(new)

Data Type:  int64
Data Type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [5]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)

print("Data Type: ",x2.dtype)
print("Data Type: ",new.dtype)
print("Data Type: ",new_one.dtype)

print(x2)
print(new)
print(new_one)


Data Type:  int64
Data Type:  float32
Data Type:  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [7]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
 
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
