Indexing


In [2]:
import numpy as np
var = np.array([1,2,34,4])
print(var[1])
print(var[-3])

2
2


In [5]:
var1 = np.array([[2,4,5],[6,7,8]])
print(var1.ndim)
print(var1)
print()
print(var1[0,2])

2
[[2 4 5]
 [6 7 8]]

5


In [7]:

var2 = np.array([[[1,2,3],[5,6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,2])


[[[1 2 3]
  [5 6 7]]]
3

7
