Iteration


In [2]:
import numpy as np
var = np.array([1,2,3,4,5])
print(var)
print()
for i in var:
    print(i)


[1 2 3 4 5]

1
2
3
4
5


In [4]:
import numpy as np
var2 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(var2)

for i in var2:
    print(i)

print()
for k in var2:
    for l in k:
        print(l)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[1 2 3 4 5]
[6 7 8 9 0]

1
2
3
4
5
6
7
8
9
0


In [9]:
var3 = np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
print(var3)
print(var3.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)
print()
for i in np.nditer(var3):
    print(i)

[[[1 2 3 4 5]
  [6 7 8 9 0]]]
3

1
2
3
4
5
6
7
8
9
0

1
2
3
4
5
6
7
8
9
0


In [10]:
var3 = np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)


[[[1 2 3 4 5]
  [6 7 8 9 0]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 0
