Join Array

In [3]:
import numpy as np
var = np.array([2,3,4,5,5])
var2 = np.array([3,4,5,6,7])

ar = np.concatenate((var,var2))
print(ar)

[2 3 4 5 5 3 4 5 6 7]


In [4]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[5,6],[7,8]])
arr = np.concatenate((vr,vr1),axis=1)
print(vr)
print()
print(vr1)
print()
print(arr)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
var_1 = np.array([1,2,3,4,5])
var_2 = np.array([1,2,3,4,5])

a_new = np.stack((var_1,var_2),axis=1)
a_new1 = np.hstack((var_1,var_2)) # row
a_new2 = np.vstack((var_1,var_2)) # column
a_new3 = np.dstack((var_1,var_2)) # height

print(a_new)
print(a_new1)
print(a_new2)
print(a_new3)


[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[1 2 3 4 5 1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]]
